import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const templateNames = ["AGENTS.md", "SOUL.md"] as const;
const extraNames = ["README.md", "EXTENSIONS.md"] as const;

const repoRoot = join(import.meta.dir, "..");
const templatesDir = join(repoRoot, "templates");
const outputPath = join(repoRoot, "src", "generated", "builtin-templates.ts");

const templateEntries = templateNames.map((name) => {
  const content = readFileSync(join(templatesDir, name), "utf-8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`;
});

const extraEntries = extraNames.map((name) => {
  const content = readFileSync(join(repoRoot, name), "utf-8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`;
});

const output = `// Generated by scripts/generate-builtin-templates.ts. Do not edit by hand.
export const TEMPLATE_DOC_NAMES = ${JSON.stringify(templateNames)} as const;
export const EXTRA_DOC_NAMES = ${JSON.stringify(extraNames)} as const;

export type TemplateDocName = (typeof TEMPLATE_DOC_NAMES)[number];
export type ExtraDocName = (typeof EXTRA_DOC_NAMES)[number];

export const BUILTIN_TEMPLATE_DOCS: Record<TemplateDocName, string> = {
${templateEntries.join("\n")}
};

export const EXTRA_DOCS: Record<ExtraDocName, string> = {
${extraEntries.join("\n")}
};
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf-8");
